name: "Bug: Fix unexpected behavior"
description: Report defects discovered in production or QA.
title: "Bug: <area> - <summary>"
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the issue and affected capability.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: List the steps and environment details.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual
      description: What should happen? What happened instead?
    validations:
      required: true
  - type: textarea
    id: artifacts
    attributes:
      label: Evidence
      description: Logs, screenshots, URLs, or other supporting info.
  - type: input
    id: spec-impact
    attributes:
      label: Spec Impact
      description: Does a spec require updates to reflect this fix?
