name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/www.reading-advantage.com
          docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/www.reading-advantage.com
          gcloud auth configure-docker --quiet
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME=static-site-service
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/static-site
          REGION=us-central1  # Change to your preferred region
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
